### PR TITLE
fixed Colliders

### PR DESCRIPTION
**Pull request by ofaura**

### CODE REVIEW

**Review by lucho1 — DISMISSED** [review]
Ojo perquè a la línea 150 de ComponentCollider.cpp hi ha com una comprovació rara xD

**Review by knela96 — DISMISSED** [review]
The condition that you found strange is correct, When adding the component collider, the rigidbody is only created when adding the new collider. that's why the check of the 2 rigidbodies and the return in case of not finding any.

**Review by knela96 — COMMENTED** [review]
I've only deleted a stupid line of code, Oscar left to check the collider he wanted

**Review by knela96 — APPROVED** [review]
Updated scales working

**Pull request merged**
