### PR TITLE
Lighting: Corrections, Improvements & Scripting

### PR DESCRIPTION
**Pull request by lucho1**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks

## Description
Include a description on what you are adding with this pull so it can be tested

Improved Lighting adding an ambient color (modifiable) for the scene, a distance multiplier and scripting support.

Also, corrected some editor values for the light component to make it better :D #UX

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by lucho1** [comment]
Didn't checked on a game build, but the changes are not related to that, so it should not give any problems...

**Comment by lucho1** [comment]
...said somebody just before a merge that crashed the whole project during 2 years

**Comment by lucho1** [comment]
So, yes, I just tested it in a game build but just the basic changes... A plane, a material, a light with the changes made, a camera... It works :)

However... SCRIPTING FUNCTIONS FOR LIGHTING ARE NOT TESTED (no time)... But since they are not needed for this delivery, I think they can pass and QA them later.

**Review by t3m1X — APPROVED** [review]
I trust Lucho with my life

**Pull request merged**
