### PR TITLE
Alpha Selector (by Material & Particle Em.) and Better Skybox :D

### PR DESCRIPTION
**Pull request by lucho1**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [ ] I have tested with latest game build's assets/scenes, no issues. 

## Description
Made a system to select the desired blending functions, equations or manual functions that the user wants to use by material and by particle emitter. Also, there is one selector in the Renderer Panel for the "general default" one.

In addition, as a gift, I made a completely new and beatuiful and shiny skybox :D... It's amazing, is the best skybox you'll ever see.

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by lucho1** [comment]
DO NOT REMOVE THAT INTENDED-UPLOADED JSON AND THOSE AMAZING NEW SKYBOX IMAGES... please :D

**Review by t3m1X — CHANGES_REQUESTED** [review]
Crashes on old JSON, check line 460 on ModuleRenderer.cpp on how to make it compatible with old JSONs

**Comment by lucho1** [comment]
That's corrected now, please check out that it loads old scenes correctly (I have already done that, but to make sure)

**Review by t3m1X — APPROVED** [review]
Finally! It works!

**Pull request merged**
