### PR TITLE
Materials scripting functions

### PR DESCRIPTION
**Pull request by lucho1**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [ ] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [ ] I have tested with latest game build's assets/scenes, no issues. 

## Description
Implemented Scripting Functions for Materials

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by lucho1** [comment]
Not gonna say it's merged because there are many pull requests and the branch will stop being up-to-date at any time

**Comment by lucho1** [comment]
I've tested it, but please, make sure is tested over and over again, I wouldn't like to introduce any bug. Mainly because I use some const char* for some functions, and I would like to make sure that works fine (again: I tested it, but better 4 eyes than 2)

**Comment by lucho1** [comment]
This pull is not necessary before Alpha2 delivery

**Review by t3m1X — APPROVED** [review]
Works on my machine, thanks for completing the autocomplete file, I'm sure @DidacRomero appreciates it

**Pull request merged**
