### PR TITLE
Particles fixes & small implementations

### LINKED ISSUE #72: Want to visually see the particle emitter area
## Enhancement Description
Want to visually see the particle emitter area when modifying

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [x] Visual 

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [x] **User Quality of Life Upgrade:** It would improve the User Experience.

## Observations and Additional Information
Jaume

### LINKED ISSUE #337: Particle emitter size not working
## Bug Description
Cannot change the size of a particle emitter

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [X] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [X] Cosmetic 

## Reproduction

 1.  Create a particle emitter
 
 2.  Change its size

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Particle emitter changes its size accordingly

### Actual result:
It stays the same

### PR DESCRIPTION
**Pull request by X0KA**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
Added some fixes/improvements:
-Particle emitter area draw
-Particles can follow the emitter
-Fixed the emitter size bug 

## Related issues
Resolves #337
Closes #72

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
Code seems good, but the save/load might fail with old scenes

**Review by lucho1 — COMMENTED** [review]
Why that emitter spawn position is there, in Particle.h?

**Review by lucho1 — DISMISSED** [review]
Ok, I've already seen what's that "emitterSpawnPosition" for.

Code now seems good for me. @t3m1X is on your hands :)

**Review by t3m1X — APPROVED** [review]
Minor bug fixed, it works on my machine now :)

**Review by lucho1 — APPROVED** [review]

**Pull request merged**
