### PR TITLE
Play on awake()

### PR DESCRIPTION
**Pull request by knela96**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
Play on Awake for particles and fixed again ordering

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by knela96** [comment]
els 2 ultims commits son irellevants pero per no fer un revert i que petes tot es queda igual

**Review by lucho1 — COMMENTED** [review]
Code looks good

**Comment by lucho1** [comment]
Tested and passed

**Review by t3m1X — DISMISSED** [review]
Well, it does work on my machine so as long as it works on yours.

**Review by lucho1 — APPROVED** [review]

**Pull request merged**
