### PR TITLE
Audio

### PR DESCRIPTION
**Pull request by sherzock**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks

## Description
Solved audio memleaks and pause errors, added component audiolistener to editor camera and changed imgui default style 

## Related issues
Audio memleaks
Audio stop and play now stops audios and resumes audios

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
Code reviewed and OK (except for the config file :( )

**Comment by t3m1X** [comment]
It does break on build so for now it is on hold

**Comment by sherzock** [comment]
Solved issue with builds

**Review by t3m1X — APPROVED** [review]
Builds do not break anymore, it has my seal of approval

**Pull request merged**
