### PR TITLE
Ported engine into x64

### PR DESCRIPTION
**Pull request by t3m1X**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [X] Merged branch development into it 
- [X] Compiles both in Release and Debug mode
- [X] Game build can be created and it launches without issue
- [X] I have checked and it has no memory leaks
- [X] I have tested with latest game build's assets/scenes, no issues. 

## Description
Engine is now ported to x64
Memory goes brr
Please remember to change your working directory in x64 before compiling

### CODE REVIEW

**Comment by lucho1** [comment]
Read Title - Read Description

**Review by AitorSimona — DISMISSED** [review]
Works on my machine

**Review by AitorSimona — APPROVED** [review]
Works on my machine electric bogaloo

**Comment by t3m1X** [comment]
Cannot merge, redoing the branch ASAP

**Pull request closed without merging**
