### PR TITLE
Reverted euler angles back to old behaviour

### LINKED ISSUE #295: "Gimbalock" or "Bad Euler Translation" fix working incorrectly
## Bug Description
I don't know what has been done to fix the Euler Translation bug for rotations but is not working as we Gameplay Programers expect it to be. Instead of snapping in and out of 180 on **X** and **Z** angles while the Y angle doesn't go above 90 (either + or -), it now does essentially the same but with the X and Y angles accumulating values indefinitely or working in otherwise unexpected ways.

This needs to be fixed so that the Y angle goes from 0 to whatever with the X and Z angles remaining intact, and ideally any angle being able to be modified with the value of the other two not changing at all.

If such outcome, the desired one, cannot be achieved please revert the previous "fix", as having the X and Z angles snap in and out of 180 was the signal for the workaround to interpret the angles correctly.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Create a Cube
 
 2. Using the Gizmo, rotate the Y axis VERY fast
 
 3. Alternatively: Use a script to move something through Joysticks, then move up and down (essentially doing 180 turns), or just spin around very quickly, changing directions randomly.

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
GO Euler Rotations in the UI only change the Y value (the one being rotated) no matter how quickly the turns are made.

### Actual result:
GO Euler Rotations change the X and Z values when doing full 180 turns in a single frame, or generally very quickly. This is the same bug we had previously, but now instead of having the X and Z values staying at -180 or 180, they gradually increase (probably by 180/-180) with each new sharp rotation.

## Screenshots and Illustrations:
GIF 29-04-2020 13-42-41

## Build
0.5.2

## Observations and Additional Information
As mentioned above, if the bug can't be fixed for whatever reason, please revert it to where it was before. Snapping from/to 180/-180 allowed me to build a workaround, which can be adapted to this "new bug", but if we have a bug at all I rather use the previous fix.

### PR DESCRIPTION
**Pull request by t3m1X**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [X] Merged branch development into it 
- [X] Compiles both in Release and Debug mode
- [ ] Game build can be created and it launches without issue
- [X] I have checked and it has no memory leaks
- [ ] I have tested with latest game build's assets/scenes, no issues. 

## Description
Include a description on what you are adding with this pull so it can be tested

## Related issues
Closes #295
Reopens #30
Reopens #85

### CODE REVIEW

**Comment by t3m1X** [comment]
I draft it so that I can work on a fix and have this as a backup.

**Comment by lucho1** [comment]
Have to talk with @t3m1X about this

**Review by lucho1 — APPROVED** [review]
It looks perfect to me

**Comment by lucho1** [comment]
Should be tested? Or is just a revert?

**Comment by t3m1X** [comment]
Afaik, this already works since you made the lasts builds with it? @lucho1

**Comment by lucho1** [comment]
You got your point

**Pull request merged**
