### PR TITLE
Canvas fix

### PR DESCRIPTION
**Pull request by DavidTello1**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
New UI workflow, tested with last build and loads prefabs correctly

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by lucho1** [comment]
Won't test it now because of time, but to start, @t3m1X see that thing flying? It's not a plane, it's a JSON in our airspace...

**Comment by lucho1** [comment]
Tested successfully, game scene loads ok and UI Elements can be used properly

**Comment by lucho1** [comment]
And a build with that scene and UI Elements can be also donette :)

**Review by t3m1X — APPROVED** [review]
It works on my machine

**Review by lucho1 — APPROVED** [review]

**Pull request merged**
