### PR TITLE
Audio

### PR DESCRIPTION
**Pull request by sherzock**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue

## Description
Implemented Audio system

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
LUCHO APPROVES

**Comment by lucho1** [comment]
Okay, if there are memory leakes, LUCHO DOESN'T APPROVES

**Review by t3m1X — CHANGES_REQUESTED** [review]
Fix those memory leaks, man

**Review by t3m1X — APPROVED** [review]
Memory leaks seem to be fixed

**Pull request merged**
