### PR TITLE
Multiple selection, Guizmo + things

### LINKED ISSUE #26: Using the Gizmo on child GOs will send the Gizmo flying away
## Bug Description
Trying to move the Gizmo on a child game object moves the Gizmo and the GO to some weird random and broken coordinates.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Drag an FBX with many childs to the scene
 
 2. Navegate the hierarchy and select a child
 
 3. Move the child using the Gizmo

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Gizmo can move objects regularly.

### Actual result:
Gizmo and object are teleported somewhere.

## Screenshots and Illustrations:
image

## Build
BrokenEngine_v0.1.7

## Observations and Additional Information
Used Geralt_Anims1 child hierarchy for testing.

### LINKED ISSUE #125: Gizmo is positioned on global coordinates regardless of hierarchy
## Bug Description
Gizmos seem to ignore the transform hierarchy of GOs or use the global position. Either way, the issue is that when using parenting, the Gizmo is NOT situated where the GO really is.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Create 2 GO
 
 2. Move the first somewhere out of World 0,0,0
 
 3. Make the 2nd child of the first

 4. Put 2nd in local 0,0,0 coordinates using Inspector end keep it selected

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Gizmo is on the position of the 1st GO, as its child currently selected is on coordinates 0,0,0 and therefore on the exact position of the 1st GO.

### Actual result:
Gizmo locates itself in the World's 0,0,0 coordinates, ignoring the parenting of the 2 GOs and taking the 2nd GO local 0,0,0 coordinates as global coordinates.

## Screenshots and Illustrations:
image

## Build
0.3.0

## Observations and Additional Information
This is very probably related to #26

### LINKED ISSUE #213: Focus (F Key) not working
## Bug Description
The camera focus doesn't work

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Make a game object and select it, move the camera randomly
 
 2. Press F
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Camera should focus

### Actual result:
Camera does nothing

## Build
- **Please specify the build:** ``Insert the build here``
v0.4.x

### PR DESCRIPTION
**Pull request by ponspack9**
## Testing checklist

- [x] Merged branch development into it 
- [x] Compiles in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks

## Description
- Multi renaming
- Multi active/inactive
- Multi static/dynamic (edited feedback for bug purposes)
- Focus object bug fixed
- Visual scene feedback rectangle of selection 
- Script name in component title 
- Selection counter or selected object in hierarchy
- Change parent to the dragged one 
- Change parent without selecting, directly dragging
- **Guizmo transformation to all**
    - Gets a little bugged when selecting parent and childs together( idk why but if you rotate the guizmo with a smal radius respect to center it gets crazy, but if you rotate the same amount of degrees but the mouse is far away it stays more stable and rotates properly)

## Related issues
#213 Solved
#125 Solved
#26   Solved (i think, not actually tested)

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
**Notes for tomorrow:**

* Check or ask Oscar if the ComponentScript change of "name" variable don't give any problems (specially at external stuff using it)
* Check or ask Oscar if the TransformGlobal() function (at GameObject.cpp) is not called by any external shit that needs to pass a pointer to a GameObject (as he changed)... Specially for scripting calls 
* About Engine Camera Focus: Make sure that, if nothing selected, it looks at the scene's center (0,0,0) to avoid possible errors on framing without selection
* Take a look at ModuleSelection.h comments to know what to put in the Changelog about this pull

**Comment by ponspack9** [comment]
- I think that the variable "name" or "script_name" was only used when assigning the name of the script when creating it, it was never used more than when displaying it at inspector
- I do not really understand the TransformGlobal() issue, i modified it to save its global transform to at the end of the function apply it, i'm not making any external calls from or to it other than SetGlobalTransform().
- That is already done that way
- I'm updating the changelog then

**Comment by lucho1** [comment]
Yep, the first 2 points, were just a reminder for me (and maybe Didac & Sergi) to test them properly, since scripting is a bit fragile and we wanted to see if this name variable change was not crashing or something (because of Lua scripts), as well as the Transform function.

The third point seems great, just wanted to test it :)

And the final one was just a reminder for me to update the releases changelog, thanks for the comments in the header :)

**Comment by lucho1** [comment]
Tested in debug and release, working properly

**Review by t3m1X — APPROVED** [review]
All works, including in a build

**Pull request merged**
