### PR TITLE
Hotfix dt bug

### PR DESCRIPTION
**Pull request by DidacRomero**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks

## Description
Include a description on what you are adding with this pull so it can be tested

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by AitorSimona — CHANGES_REQUESTED** [review]
Beautiful json, have you tested these changes with the latest game build/scene?

**Review by t3m1X — CHANGES_REQUESTED** [review]
Fixed that JSON for you, but @AitorSimona is holding me at gunpoint until you prove that you have tested this with the latest build

**Comment by lucho1** [comment]
I have seen that they have tried it I think

**Comment by AitorSimona** [comment]
Fine then

**Review by t3m1X — APPROVED** [review]
They tested in build, so approved.

**Pull request merged**
