### PR TITLE
Particles Curve Editor

### PR DESCRIPTION
**Pull request by knela96**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
Implemented Particle Curve Editor

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by lucho1 — CHANGES_REQUESTED** [review]
Assets folders should not be changed (in general)... For instance, shaders and audio files (idk why) are deleted (?) and that could cause problems... @t3m1X pls revert that if you can :(

Another comment: The function of resource manager GetTextureResourceByName() is already done in the pull of MaterialsScripting... Be careful, we will have to delete one of them

**Comment by lucho1** [comment]
Nvm, that function GetTextureResourceByName() is not in the materials pull, is in here because I myself placed it here, in this very same pull :D

**Review by lucho1 — COMMENTED** [review]
Checked and now seems ok

**Review by t3m1X — APPROVED** [review]
All seems to be working as expected.

**Review by lucho1 — APPROVED** [review]

**Pull request merged**
