### PR TITLE
Ui improvements

### LINKED ISSUE #277: UI cant move as a group
## Enhancement Description
every time the UI is moved, Oscar need to manually go element by element to fix its position. the must be a way to make a hole group of the ui and move it thorught the screen

## Type of Enhancement 
Select the type of enhancement with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [x] UI/UX
* [ ] Other

## Why do you propose this enhancement?
Select why do you want to propose this enhancement with and "x" ([x])

- [ ] **Increased Performance**: Optimization which would improve execution performance.
- [x] **New Feature**: It's an additional feature that fits in the product.
- [x] **Developer Quality of Life Upgrade**: It would optimize current or new implementations.
- [x] **User Quality of Life Upgrade:** It would improve the User Experience.
- [ ] **Other**: *Describe reason here*

## Implementation Instructions and Guidelines
please if there is nany way to make the UI into a group, and be able to modifiy the position of all of them at the time, it will save a lot of hours of work

## Observations and Additional Information
Can ask oscar larios for more sugestions

### LINKED ISSUE #307: Buttons are not updated if they are not childs of root
## Bug Description
Checked in code, they are only updated if root is their parent...

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [X] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [X] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Create a button and make a canvas its parent
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Buttons work whether root is their parent or not

### Actual result:
They do not work if root is not their parent

## Build
- **Please specify the build:** ``Insert the build here``
dev commit 2225

### PR DESCRIPTION
**Pull request by AitorSimona**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [X] Merged branch development into it 
- [X] Compiles both in Release and Debug mode
- [X] Game build can be created and it launches without issue
- [X] I have checked and it has no memory leaks
- [X] I have tested with latest game build's assets/scenes, no issues. 

## Description
Include a description on what you are adding with this pull so it can be tested
ui elements can be moved through canvas parent, canvas is required to see ui
## Related issues
Does your branch fix any existing issues? If so please link them

closes #307 
closes #277

### CODE REVIEW

**Review by t3m1X — DISMISSED** [review]
UI Components are only updated when they are a child of the root GO and they do not display unless they are inside a canvas, so you do need to put them in a canvas to see them and then take them out to actually make them work and have their state updated. Draggable buttons also work a bit weird, moving randomly.

**Comment by lucho1** [comment]
They actually even don't check if they are taken out from the canvas

**Comment by lucho1** [comment]
image

**Comment by AitorSimona** [comment]
About the IMAGE above. 

This is ALREADY in DEVELOPMENT, thus having no direct relationship with what was asked from this branch

**Comment by AitorSimona** [comment]
> UI Components are only updated when they are a child of the root GO and they do not display unless they are inside a canvas, so you do need to put them in a canvas to see them and then take them out to actually make them work and have their state updated. Draggable buttons also work a bit weird, moving randomly.

About not displaying unless inside a canvas... This is the expected functionality. About the preupdate, which I understand is related to lucho's image, this is ALREADY in DEVELOPMENT. No direct relationship with this pull. Create an issue/task/branch to solve this. This branch is expected to  allow moving childs through canvas, nothing else

**Comment by lucho1** [comment]
Yes, you're right, however, this Pre-Update (which is already in development), along with the changes in this branch, makes the UI not working... I mean, in order to make buttons, now they must be inside a canvas (which is correct), but the fact of being inside the canvas, makes them not working due to the lines of the Pre-Update.

This should be fixed before merging, it shouldn't take much time.

**Comment by lucho1** [comment]
If we put this branch into development, we would make an Engine build in which the UI doesn't works, while if we keep development as is, at least there will be a way to make it work (that's why it should be fixed in this branch, before merging)

**Comment by AitorSimona** [comment]
Create an issue and assign me then

**Comment by lucho1** [comment]
Tested in debug, release & build modes and working... Also in a game build and working too.

**Review by lucho1 — DISMISSED** [review]

**Review by lucho1 — APPROVED** [review]
Tested and reviewed, for me seems OK

**Review by lucho1 — APPROVED** [review]

**Pull request merged**
