### PR TITLE
enabled  full transparencies, preparing for partial transparency and …

### PR DESCRIPTION
**Pull request by AitorSimona**
…mesh ordering

## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [X] Merged branch development into it 
- [X] Compiles both in Release and Debug mode
- [X] Game build can be created and it launches without issue
- [X] I have checked and it has no memory leaks

## Description
Include a description on what you are adding with this pull so it can be tested
Enabled textures with full transparent parts through new shader

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
Code reviewed... Seems OK, but I see a problem:

Still, meshes with materials with transparencies, have to be rendered with the Standard shader, since they need to be affected by light and they need to do all standard shader calculations (normals, specular...)

**Comment by lucho1** [comment]
I see that they actually don't use it... I mean, the only thing has been done is the draw ordering so they still are rendered with the standard shader... But actually, what the Transparency Shader does can be easily merged into the Standard one since the discard can be placed at the beginning of the Fragment part of the standard shader

**Review by t3m1X — CHANGES_REQUESTED** [review]
I understand @lucho1 is requesting changes?

**Comment by AitorSimona** [comment]
Transparencies through standard shader, just check the checkbox :)

**Review by t3m1X — APPROVED** [review]
It works on my machine  ¯\\\_(ツ)_/¯

**Pull request merged**
