### PR TITLE
Ui shader

### PR DESCRIPTION
**Pull request by lucho1**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks

## Description
Include a description on what you are adding with this pull so it can be tested
Made a Shader for UI and Text, so they don't use the standard one (with unnecessary calculations for UI such as lighting)

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by lucho1** [comment]
Wait, I have to fix something, wait until another comment

**Comment by lucho1** [comment]
Donete :)

**Comment by lucho1** [comment]
Btw, the checkboxes are true, I tested it all in case you doubt it (just for you to know)

**Review by t3m1X — APPROVED** [review]
Made a small change, otherwise all seems good.

**Pull request merged**
