### PR TITLE
Particles Animation + Multiple Gradients

### LINKED ISSUE #169: Particle System Renderer Scale Particle
## Bug Description
If we change the size of the Renderer Scale inside Particle Component, the particle is beeing createn with an Offset, depending on the values we pot on Scale(X,Y), if the values increase, the offset does the same. I think that it sould Scale from the center point and be created on Emitter position (0,0,0)

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [X] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [X] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [X] Cosmetic 

## Reproduction

 1. Create Particle Component
 
 2. Change values on Rendered Scale X and Y
 
 3. PLAY

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [X] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Appear on the same position of the particle emitter (0,0,0) position?

### Actual result:
It moves with and offset, if Scale is 1,1, it appears on the correct spot, but when these values are 10,10 the particle will be created from 10,10 instead of 0,0 

## Screenshots and Illustrations:
https://imgur.com/a/n1OaaOV

## Build
- **Please specify the build:** ``3.0.6``

## Observations and Additional Information

Close #289

### PR DESCRIPTION
**Pull request by knela96**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
Included Sprite Animations  + Multiple Gradients Over Time

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Comment by knela96** [comment]
No borrar, que en release pasa algo

**Comment by knela96** [comment]
Sergi told me that the drops on framerate was caused by V-sync. FALSE ALARM

**Review by t3m1X — CHANGES_REQUESTED** [review]
Changing lifetime of particles when there are no gradients set crashes the engine due to division by zero.

**Comment by knela96** [comment]
tell juanito why it was not working, now it works

**Review by t3m1X — APPROVED** [review]
This all works as nintended

**Pull request merged**
