### PR TITLE
Particles fixes & small implementations

### PR DESCRIPTION
**Pull request by X0KA**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
A few small changes on the particle emitters:
- Animations: random startframe
- Rotation: random start rotation

And some changes in the editor function, not really important

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by lucho1 — CHANGES_REQUESTED** [review]
The JSON should not be uploaded (i'll revert it tomorrow)

But however... I need to properly test the save/load of the changes and actually talk to @X0KA about the priority changes.

**Comment by AitorSimona** [comment]
Would be nice to have a description :(

**Review by AitorSimona — APPROVED** [review]
No crashes on latest scene. I've been told it has been tested with some of our actual particles, approved

**Comment by lucho1** [comment]
I have been testing too, works perfect

**Review by lucho1 — APPROVED** [review]

**Pull request merged**
