### PR TITLE
Particles scripting

### PR DESCRIPTION
**Pull request by X0KA**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
Added scripting functions for particles

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
Code seems OK, but I have to do a couple of minor corrections (specially in Fail Safe on Setting Texture function)

**Review by lucho1 — COMMENTED** [review]
Now I have reviewed the code (didn't tested that much in fact, just compilation)... So, @t3m1X, is your pull now :D

**Comment by lucho1** [comment]
Also added and corrected a couple of things

**Comment by t3m1X** [comment]
Now duplicating #328

**Pull request closed without merging**
