### PR TITLE
In Game UI - Image and button can be in 3D space

### PR DESCRIPTION
**Pull request by ponspack9**
## Testing checklist

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [x] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
UI compnents image and button can be placed around both in 3D and 2D space, no need of canvas and respects the transformations of the parent, acting like a normal gameobject.

**IMPORTANT**
- The collider of the button is useless/not reliable when positioning it in 3D space, BUT it should work with a controller since I only edited the draw process of the image, I could not test the button functionalities with a controller because i do not own one.
- Fixed aspect ratio 16:9 can be reversed back to free aspect as it was made to fix this problem with button positioning, now nothing is using it and looks streched.

## Related issues
Not an issue but a UI positioning problem

### CODE REVIEW

**Review by t3m1X — DISMISSED** [review]
It works on my machine

**Review by lucho1 — DISMISSED** [review]

**Comment by lucho1** [comment]
Ok, code and tests seems to be OK, but we still have the same problem than the "is_null" pull: when unloading Main Menu scene (of the scene setup 1.0), crashes on an object called "Render"

**Comment by lucho1** [comment]
As soon as that's fixed and as soon as the skybox commits are reverted, this pull can be merged

**Review by lucho1 — APPROVED** [review]
Tested and fine

**Pull request merged**
