### PR TITLE
Particle emitters aabb

### PR DESCRIPTION
**Pull request by lucho1**
## Testing checklist
Please make sure you mark with an "x" ([x]) all the tests you have done in the branch so it is easier to test it before merge

- [x] Merged branch development into it 
- [x] Compiles both in Release and Debug mode
- [X] Game build can be created and it launches without issue
- [x] I have checked and it has no memory leaks
- [x] I have tested with latest game build's assets/scenes, no issues. 

## Description
Particles AABB correction and used each particle for camera culling

## Related issues
Does your branch fix any existing issues? If so please link them

### CODE REVIEW

**Review by lucho1 — COMMENTED** [review]
Checked the code, seems fine (I know I created pull, but I'm not the author of the code)

**Comment by lucho1** [comment]
Tested in scene setup v0.6.6

**Comment by lucho1** [comment]
It works

**Review by AitorSimona — APPROVED** [review]
It works on my machine.

**Pull request merged**
